## NAME: SIDDHI GAWADE
## ROLL NO.: 24102A2001
## BRANCH: BE CMPN-A
## SUBJECT: PROG WITH R

## Missing data

In [ ]:
x = NA

In [ ]:
is.na(x)

[1] TRUE

In [ ]:
y = c(11, NA, 13, NA)

In [ ]:
is.na(y)

[1] FALSE  TRUE FALSE  TRUE

In [ ]:
a = c(11, NA, 13, NA)

In [ ]:
mean(a)

[1] NA

In [ ]:
mean(x, na.rm = TRUE)

[1] 12

## VERY IMPORTANT NOTE

### Note that NA and NULL are not the same.
### NA is a placeholder for something that exists but is missing.
### NULL stands for something that never existed at all

## Missing data: Location of missing values

In [ ]:
b = c(10, NA, 12, NA)
which(is.na(b))

[1] 2 4

In [ ]:
sum(is.na(b))

[1] 2

In [ ]:
complete.cases(b)

[1]  TRUE FALSE  TRUE FALSE

In [ ]:
d = c(11, NA, 13, NA)
d

[1] 11 NA 13 NA

In [ ]:
y = na.omit(d)
y

[1] 11 13
attr(,"na.action")
[1] 2 4
attr(,"class")
[1] "omit"

In [ ]:
attr(y,"na.action")

[1] 2 4
attr(,"class")
[1] "omit"

## Missing data: Handling values

In [ ]:
x = c(11, NA, 12, NA)
y = na.omit(x)
y

[1] 11 12
attr(,"na.action")
[1] 2 4
attr(,"class")
[1] "omit"

In [ ]:
mean(x)
mean(y)

[1] NA

[1] 11.5

## Conditional Executions – If and If‐Else

In [ ]:
x = 5
if(x > 4) x * 3

[1] 15

In [ ]:
x = 3
if(x > 4) x * 3
## No response is obtained.

In [ ]:
x = 5
if (x > 4) {x*3}

[1] 15

In [ ]:
x = 3
if(x > 4) {x*3}

In [ ]:
x = 6
if(x > 3){
  print("The value is more than 3")
}

[1] "The value is more than 3"

In [ ]:
x = 2
if(x > 3){
  print("The value is more than 3")
}

## NO OUTPUT

## if else()

In [ ]:
x = 5
if (x==3) {x=x-1} else {x = 2*x}
x

[1] 10

In [ ]:
x = 3
if (x==3) {x=x-1} else {x=2*x}

In [ ]:
x = 6
if(x>3){
  print("The value is more than 3")
}else{
  print("The value is less than 3")
}

[1] "The value is more than 3"

In [ ]:
x = 2
if(x>3){
  print("The value is more than 3")
}else{
  print("The value is less than 3")
}

[1] "The value is less than 3"

## Nested if else if()

In [ ]:
x = 5
if( x==3){
  x = x-1
} else if (x < 3){
x = x+5
} else {x = 2*x}
x

[1] 10

In [ ]:
x = 2
if( x==3){
  x = x-1
} else if (x < 3){
x = x+5
} else {x = 2*x}
x

[1] 7

In [ ]:
x = 3
if( x==3){
  x = x-1
} else if (x < 3){
x = x+5
} else {x = 2*x}
x

[1] 2

## ifelse()

In [ ]:
x = 1:10
x

 [1]  1  2  3  4  5  6  7  8  9 10

In [ ]:
ifelse(x<6, x^2, x+1)

 [1]  1  4  9 16 25  7  8  9 10 11

In [ ]:
x = c(7,9,8,4)
ifelse(x%%2 == 0, "even number", "odd number")

[1] "odd number"  "odd number"  "even number" "even number"

## switch()

In [ ]:
switch(2,"apple","banana","orange")

[1] "banana"

In [ ]:
switch(1,"apple","banana","orange")

[1] "apple"

In [ ]:
switch("colour","colour" = "blue", "gender" ="female", "volumne"=50)

[1] "blue"

In [ ]:
switch("volume", "colour"="blue", "gender" = "female", "volume"=50)

[1] 50

In [ ]:
switch(4,"apple","banana","orange")
# NO OUTPUT

## which()

In [ ]:
x = c(10,15,8,14,6,12)
x

[1] 10 15  8 14  6 12

In [ ]:
which(x==14)

[1] 4

In [ ]:
which(x!=12)

[1] 1 2 3 4 5

In [ ]:
which(x>10)

[1] 2 4 6

In [ ]:
x = matrix(nrow=3,ncol=3, data=1:9)
x

     [,1] [,2] [,3]
[1,] 1    4    7
[2,] 2    5    8
[3,] 3    6    9

In [ ]:
which.min(x)

[1] 1

In [ ]:
which.max(x)

[1] 9

In [ ]:
which(x%%2==1)

[1] 1 3 5 7 9

In [ ]:
which(x%%2==1, arr.ind = TRUE)

     row col
[1,] 1   1
[2,] 3   1
[3,] 2   2
[4,] 1   3
[5,] 3   3